#!/opt/homebrew/bin/lua

-- SbarLua config (FelixKratz architecture), themed dark violet + green.
-- Absolute shebang: launchd does not have /opt/homebrew/bin in PATH.

local home = os.getenv("HOME")
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path
  .. ";" .. home .. "/.config/sketchybar/?.lua"
  .. ";" .. home .. "/.config/sketchybar/items/?.lua"

sbar = require("sketchybar")

sbar.begin_config()

require("bar")
require("default")
require("spaces")
require("front_app")
require("media")
require("calendar")
require("widgets")

sbar.end_config()
sbar.event_loop()
